### PR TITLE
Handle pre-/post-syscall errors

### LINKED ISSUE #797: Convert ptrace(PTRACE_SETREGSET) failures into protection faults
When `ptrace(PTRACE_SETREGSET)` fails inside `pt_debugger::post_syscall`, instead of `abort`ing, it should be converted into a protection fault. This should be done by making `pt_debugger::post_syscall` return `bool`, and if it returns `false`, `ptproc.cpp` should kill the process, generate the protection fault, and report the system call number and `errno`.

For `arm`, we are using a separate system call to change the syscall number, so we should make the `syscall` setter return `bool` and raise `OSError` with `errno` in python. Python exception in callback should be converted into a protection fault as well.

### PR DESCRIPTION
**Pull request by quantum5**
Closes #797

* `pre_syscall` errno is now tracked and failure now results in a protection fault, e.g.
  ```
  WARNING 2020-12-29 00:17:50,494 error Protection fault on: -1 (ptrace fail)
  WARNING 2020-12-29 00:17:50,495 error Arg0: 0x0000000000000000
  WARNING 2020-12-29 00:17:50,495 error Arg1: 0x0000000000000000
  WARNING 2020-12-29 00:17:50,495 error Arg2: 0x0000000000000000
  WARNING 2020-12-29 00:17:50,495 error Arg3: 0x0000000000000000
  WARNING 2020-12-29 00:17:50,495 error Arg4: 0x0000000000000000
  WARNING 2020-12-29 00:17:50,495 error Arg5: 0x0000000000000000
  ```
* `post_syscall` failures are now converted into a special protection fault, e.g.
  ```
  WARNING 2020-12-28 00:56:47,105 error Failed to alter system call: 41 (sys_socket) with error 1 (EPERM): Operation not permitted
  WARNING 2020-12-28 00:56:47,105 error Arg0: 0x0000000000000001
  WARNING 2020-12-28 00:56:47,105 error Arg1: 0x0000000000080801
  WARNING 2020-12-28 00:56:47,105 error Arg2: 0x0000000000000000
  WARNING 2020-12-28 00:56:47,105 error Arg3: 0x0000000000000006
  WARNING 2020-12-28 00:56:47,105 error Arg4: 0x0000000000000001
  WARNING 2020-12-28 00:56:47,105 error Arg5: 0x0000000000000000
  ```

### CODE REVIEW

File: dmoj/cptbox/ptdebug_x86.cpp [hunk 1]
```diff
@@ -17,30 +17,33 @@ bool pt_debugger::supports_abi(int abi) {
...
         regs_changed = false;
+        return true;
     }
 }
 
-void pt_debugger::post_syscall() {
+bool pt_debugger::post_syscall() {
     if (!regs_changed || abi_ == PTBOX_ABI_INVALID)
-        return;
+        return true;
```
Comment (Xyene) [inline dmoj/cptbox/ptdebug_x86.cpp:37]: This is only an error if `abi_ == PTBOX_ABI_INVALID`, isn't it? `!regs_changed` should be fine...

Comment (quantum5) [reply dmoj/cptbox/ptdebug_x86.cpp:37]: Return `true` means it's not going to throw.

**Review by Xyene — APPROVED** [review]
